"""Add workflow, barcode, project, and audit models

Revision ID: 4aeaf6096159
Revises: e00022b530ee
Create Date: 2026-01-22 20:44:07.710553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aeaf6096159'
down_revision: Union[str, None] = 'e00022b530ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('workflow_type', sa.Enum('PURCHASE_ORDER', 'MATERIAL_REQUISITION', 'MATERIAL_RECEIPT', 'MATERIAL_ISSUE', 'INVENTORY_ADJUSTMENT', 'QUALITY_INSPECTION', 'MATERIAL_RETURN', 'SCRAP_REQUEST', 'PROJECT_APPROVAL', 'BOM_CHANGE', name='workflowtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_threshold', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_templates'))
    )
    op.create_index(op.f('ix_workflow_templates_code'), 'workflow_templates', ['code'], unique=True)
    op.create_index(op.f('ix_workflow_templates_id'), 'workflow_templates', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'VIEW', 'EXPORT', 'IMPORT', 'LOGIN', 'LOGOUT', 'APPROVE', 'REJECT', 'SUBMIT', 'CANCEL', 'PRINT', 'SCAN', name='auditaction'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_reference', sa.String(length=200), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('changed_fields', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('barcode_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode_value', sa.String(length=255), nullable=False),
    sa.Column('barcode_type', sa.Enum('CODE128', 'CODE39', 'QR_CODE', 'DATA_MATRIX', 'EAN13', 'UPC', name='barcodetype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'VOID', name='barcodestatus'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('print_count', sa.Integer(), nullable=False),
    sa.Column('last_printed_at', sa.DateTime(), nullable=True),
    sa.Column('last_printed_by', sa.Integer(), nullable=True),
    sa.Column('scan_count', sa.Integer(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('last_scanned_by', sa.Integer(), nullable=True),
    sa.Column('last_scan_location', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_printed_by'], ['users.id'], name=op.f('fk_barcode_labels_last_printed_by_users')),
    sa.ForeignKeyConstraint(['last_scanned_by'], ['users.id'], name=op.f('fk_barcode_labels_last_scanned_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_barcode_labels'))
    )
    op.create_index(op.f('ix_barcode_labels_barcode_value'), 'barcode_labels', ['barcode_value'], unique=True)
    op.create_index(op.f('ix_barcode_labels_entity_id'), 'barcode_labels', ['entity_id'], unique=False)
    op.create_index(op.f('ix_barcode_labels_entity_type'), 'barcode_labels', ['entity_type'], unique=False)
    op.create_index(op.f('ix_barcode_labels_id'), 'barcode_labels', ['id'], unique=False)
    op.create_index(op.f('ix_barcode_labels_lot_number'), 'barcode_labels', ['lot_number'], unique=False)
    op.create_index(op.f('ix_barcode_labels_serial_number'), 'barcode_labels', ['serial_number'], unique=False)
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_at', sa.DateTime(), nullable=False),
    sa.Column('logout_at', sa.DateTime(), nullable=True),
    sa.Column('is_successful', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('token_jti', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_info', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_history_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_history'))
    )
    op.create_index(op.f('ix_login_history_id'), 'login_history', ['id'], unique=False)
    op.create_index(op.f('ix_login_history_login_at'), 'login_history', ['login_at'], unique=False)
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='projectpriority'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('project_manager_id', sa.Integer(), nullable=True),
    sa.Column('parent_project_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_project_id'], ['projects.id'], name=op.f('fk_projects_parent_project_id_projects')),
    sa.ForeignKeyConstraint(['project_manager_id'], ['users.id'], name=op.f('fk_projects_project_manager_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_project_number'), 'projects', ['project_number'], unique=True)
    op.create_table('workflow_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED', 'ON_HOLD', 'COMPLETED', name='workflowstatus'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_workflow_instances_requested_by_users')),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], name=op.f('fk_workflow_instances_template_id_workflow_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_instances'))
    )
    op.create_index(op.f('ix_workflow_instances_id'), 'workflow_instances', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_reference_id'), 'workflow_instances', ['reference_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_reference_number'), 'workflow_instances', ['reference_number'], unique=False)
    op.create_index(op.f('ix_workflow_instances_reference_type'), 'workflow_instances', ['reference_type'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('approver_role', sa.String(length=50), nullable=True),
    sa.Column('approver_user_id', sa.Integer(), nullable=True),
    sa.Column('amount_threshold', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('escalation_hours', sa.Integer(), nullable=True),
    sa.Column('escalate_to_user_id', sa.Integer(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('allow_delegation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], name=op.f('fk_workflow_steps_approver_user_id_users')),
    sa.ForeignKeyConstraint(['escalate_to_user_id'], ['users.id'], name=op.f('fk_workflow_steps_escalate_to_user_id_users')),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], name=op.f('fk_workflow_steps_template_id_workflow_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_steps'))
    )
    op.create_index(op.f('ix_workflow_steps_id'), 'workflow_steps', ['id'], unique=False)
    op.create_table('barcode_scan_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode_label_id', sa.Integer(), nullable=False),
    sa.Column('scanned_by', sa.Integer(), nullable=False),
    sa.Column('scan_timestamp', sa.DateTime(), nullable=False),
    sa.Column('scan_location', sa.String(length=100), nullable=True),
    sa.Column('scan_device', sa.String(length=100), nullable=True),
    sa.Column('scan_action', sa.String(length=50), nullable=False),
    sa.Column('is_successful', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['barcode_label_id'], ['barcode_labels.id'], name=op.f('fk_barcode_scan_logs_barcode_label_id_barcode_labels')),
    sa.ForeignKeyConstraint(['scanned_by'], ['users.id'], name=op.f('fk_barcode_scan_logs_scanned_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_barcode_scan_logs'))
    )
    op.create_index(op.f('ix_barcode_scan_logs_id'), 'barcode_scan_logs', ['id'], unique=False)
    op.create_table('bill_of_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('revision', sa.String(length=10), nullable=False),
    sa.Column('bom_type', sa.Enum('ENGINEERING', 'MANUFACTURING', 'SERVICE', 'SALES', name='bomtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'RELEASED', 'OBSOLETE', name='bomstatus'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('base_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('released_by', sa.Integer(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_bill_of_materials_approved_by_users')),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_bill_of_materials_part_id_parts')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_bill_of_materials_project_id_projects')),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], name=op.f('fk_bill_of_materials_released_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_of_materials'))
    )
    op.create_index(op.f('ix_bill_of_materials_bom_number'), 'bill_of_materials', ['bom_number'], unique=True)
    op.create_index(op.f('ix_bill_of_materials_id'), 'bill_of_materials', ['id'], unique=False)
    op.create_table('data_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_log_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_logs.id'], name=op.f('fk_data_change_logs_audit_log_id_audit_logs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_change_logs'))
    )
    op.create_index(op.f('ix_data_change_logs_audit_log_id'), 'data_change_logs', ['audit_log_id'], unique=False)
    op.create_index(op.f('ix_data_change_logs_id'), 'data_change_logs', ['id'], unique=False)
    op.create_table('workflow_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_instance_id', sa.Integer(), nullable=False),
    sa.Column('workflow_step_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('delegated_from_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SKIPPED', 'DELEGATED', name='approvalstatus'), nullable=False),
    sa.Column('decision_at', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('is_escalated', sa.Boolean(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('original_approver_id', sa.Integer(), nullable=True),
    sa.Column('signature_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_workflow_approvals_approver_id_users')),
    sa.ForeignKeyConstraint(['delegated_from_id'], ['users.id'], name=op.f('fk_workflow_approvals_delegated_from_id_users')),
    sa.ForeignKeyConstraint(['original_approver_id'], ['users.id'], name=op.f('fk_workflow_approvals_original_approver_id_users')),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], name=op.f('fk_workflow_approvals_workflow_instance_id_workflow_instances')),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['workflow_steps.id'], name=op.f('fk_workflow_approvals_workflow_step_id_workflow_steps')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_approvals'))
    )
    op.create_index(op.f('ix_workflow_approvals_id'), 'workflow_approvals', ['id'], unique=False)
    op.create_table('bom_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('item_number', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('child_bom_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('scrap_factor', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('reference_designator', sa.String(length=100), nullable=True),
    sa.Column('find_number', sa.String(length=20), nullable=True),
    sa.Column('substitutes_allowed', sa.Boolean(), nullable=False),
    sa.Column('operation_sequence', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['bill_of_materials.id'], name=op.f('fk_bom_items_bom_id_bill_of_materials')),
    sa.ForeignKeyConstraint(['child_bom_id'], ['bill_of_materials.id'], name=op.f('fk_bom_items_child_bom_id_bill_of_materials')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_bom_items_material_id_materials')),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_bom_items_part_id_parts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bom_items'))
    )
    op.create_index(op.f('ix_bom_items_id'), 'bom_items', ['id'], unique=False)
    op.create_table('material_requisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_number', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('bom_id', sa.Integer(), nullable=True),
    sa.Column('work_order', sa.String(length=100), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('required_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_material_requisitions_approved_by_users')),
    sa.ForeignKeyConstraint(['bom_id'], ['bill_of_materials.id'], name=op.f('fk_material_requisitions_bom_id_bill_of_materials')),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], name=op.f('fk_material_requisitions_issued_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_material_requisitions_project_id_projects')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_material_requisitions_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_requisitions'))
    )
    op.create_index(op.f('ix_material_requisitions_id'), 'material_requisitions', ['id'], unique=False)
    op.create_index(op.f('ix_material_requisitions_requisition_number'), 'material_requisitions', ['requisition_number'], unique=True)
    op.create_index(op.f('ix_material_requisitions_work_order'), 'material_requisitions', ['work_order'], unique=False)
    op.create_table('material_requisition_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_requested', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('quantity_approved', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('quantity_issued', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name=op.f('fk_material_requisition_items_inventory_id_inventory')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_material_requisition_items_material_id_materials')),
    sa.ForeignKeyConstraint(['requisition_id'], ['material_requisitions.id'], name=op.f('fk_material_requisition_items_requisition_id_material_requisitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_requisition_items'))
    )
    op.create_index(op.f('ix_material_requisition_items_id'), 'material_requisition_items', ['id'], unique=False)
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('designation', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('reports_to_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('approval_limit', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('can_approve_workflows', sa.Boolean(), nullable=True, server_default='false'))
    op.execute("UPDATE users SET can_approve_workflows = false WHERE can_approve_workflows IS NULL")
    op.alter_column('users', 'can_approve_workflows', nullable=False)
    op.add_column('users', sa.Column('signature_image', sa.String(length=500), nullable=True))
    # Create the department enum type first
    department_enum = sa.Enum('OPERATIONS', 'PROCUREMENT', 'QUALITY_ASSURANCE', 'ENGINEERING', 'PRODUCTION', 'STORES', 'FINANCE', 'ADMINISTRATION', name='department')
    department_enum.create(op.get_bind(), checkfirst=True)
    # Alter the column with USING clause for PostgreSQL
    op.execute("ALTER TABLE users ALTER COLUMN department TYPE department USING department::text::department")
    op.drop_constraint('uq_users_employee_id', 'users', type_='unique')
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_foreign_key(op.f('fk_users_reports_to_id_users'), 'users', 'users', ['reports_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_reports_to_id_users'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.create_unique_constraint('uq_users_employee_id', 'users', ['employee_id'])
    op.execute("ALTER TABLE users ALTER COLUMN department TYPE VARCHAR(100) USING department::text")
    # Drop the department enum type
    sa.Enum(name='department').drop(op.get_bind(), checkfirst=True)
    op.drop_column('users', 'signature_image')
    op.drop_column('users', 'can_approve_workflows')
    op.drop_column('users', 'approval_limit')
    op.drop_column('users', 'reports_to_id')
    op.drop_column('users', 'designation')
    op.drop_column('users', 'phone')
    op.drop_index(op.f('ix_material_requisition_items_id'), table_name='material_requisition_items')
    op.drop_table('material_requisition_items')
    op.drop_index(op.f('ix_material_requisitions_work_order'), table_name='material_requisitions')
    op.drop_index(op.f('ix_material_requisitions_requisition_number'), table_name='material_requisitions')
    op.drop_index(op.f('ix_material_requisitions_id'), table_name='material_requisitions')
    op.drop_table('material_requisitions')
    op.drop_index(op.f('ix_bom_items_id'), table_name='bom_items')
    op.drop_table('bom_items')
    op.drop_index(op.f('ix_workflow_approvals_id'), table_name='workflow_approvals')
    op.drop_table('workflow_approvals')
    op.drop_index(op.f('ix_data_change_logs_id'), table_name='data_change_logs')
    op.drop_index(op.f('ix_data_change_logs_audit_log_id'), table_name='data_change_logs')
    op.drop_table('data_change_logs')
    op.drop_index(op.f('ix_bill_of_materials_id'), table_name='bill_of_materials')
    op.drop_index(op.f('ix_bill_of_materials_bom_number'), table_name='bill_of_materials')
    op.drop_table('bill_of_materials')
    op.drop_index(op.f('ix_barcode_scan_logs_id'), table_name='barcode_scan_logs')
    op.drop_table('barcode_scan_logs')
    op.drop_index(op.f('ix_workflow_steps_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_workflow_instances_reference_type'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_reference_number'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_reference_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_id'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index(op.f('ix_projects_project_number'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_login_at'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_id'), table_name='login_history')
    op.drop_table('login_history')
    op.drop_index(op.f('ix_barcode_labels_serial_number'), table_name='barcode_labels')
    op.drop_index(op.f('ix_barcode_labels_lot_number'), table_name='barcode_labels')
    op.drop_index(op.f('ix_barcode_labels_id'), table_name='barcode_labels')
    op.drop_index(op.f('ix_barcode_labels_entity_type'), table_name='barcode_labels')
    op.drop_index(op.f('ix_barcode_labels_entity_id'), table_name='barcode_labels')
    op.drop_index(op.f('ix_barcode_labels_barcode_value'), table_name='barcode_labels')
    op.drop_table('barcode_labels')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_workflow_templates_id'), table_name='workflow_templates')
    op.drop_index(op.f('ix_workflow_templates_code'), table_name='workflow_templates')
    op.drop_table('workflow_templates')
    # ### end Alembic commands ###
